fl_reports_reports_routes:
  resource: "@FLReportsBundle/Resources/config/routing/reports.yml"
  defaults:
    _require_user_group_permissions:
      - "PERMISSION_TAB_REPORTS_READ"

fl_reports_reports_rest_routes:
  resource: "@FLReportsBundle/Resources/config/routing/reports-rest.yml"
  prefix: /api/{version}
  defaults:
    _require_user_group_permissions:
      - "PERMISSION_TAB_REPORTS_READ"
    version: "v1.0"