imports:
    # If there are every implementations for other ORMs/ODMs these will have to be included manually.
    - { resource: 'services/doctrine_orm/data-transformer.yml' }
    - { resource: 'services/doctrine_orm/storage.yml' }