services:
  fl_reports.data_transformer.request_to_report.doctrine_orm:
    class: FL\ReportsBundle\DataTransformer\RequestTransformer\RequestToReport
    arguments:
      - "@fl_qbjs_parser.javascript_builders"
      - "@fl_reports.storage.doctrine_orm.report"
      - "%fl_reports.report_class%"
  fl_reports.data_transformer.request.to_pagination_query:
    class: FL\ReportsBundle\DataTransformer\RequestTransformer\RequestToPaginationQuery
  fl_reports.data_transformer.build_report_query.to_response_array.doctrine_orm:
    class: FL\ReportsBundle\DataTransformer\BuildReportQueryTransformer\QueryToResponseArray
    arguments:
      - "@fl_qbjs_parser.json_query_parser"
      - "@vich_uploader.templating.helper.uploader_helper"
      - "@exercise_html_purifier.default"
      - "@fl_reports.storage.doctrine_orm.report_results"
      - "@event_dispatcher"
