fl_reports_rest_reports_show:
  path: /reports_rest/{reportName}
  methods: [GET, HEAD]
  defaults:
    _controller: FL\ReportsBundle\Action\Reports\Rest\Show:__invoke
    _format: "json"

fl_reports_rest_reports_delete:
  path: /reports_rest/{reportName}
  methods: [DELETE]
  defaults:
    _controller: FL\ReportsBundle\Action\Reports\Rest\Delete:__invoke
    _format: "json"
  options:
      expose: true

fl_reports_rest_reports_save:
  path: /reports_rest/{reportName}
  methods: [PUT]
  defaults:
    _controller: FL\ReportsBundle\Action\Reports\Rest\Save:__invoke
    _format: "json"
  options:
      expose: true

fl_reports_rest_reports_build:
  path: /reports_rest_build
  methods: [POST]
  defaults:
    _controller: FL\ReportsBundle\Action\Reports\Rest\Build:__invoke
    _format: "json"
  options:
      expose: true