tripr_hq_api_reports_show:
  path: /reports/{reportName}
  methods: [GET, HEAD]
  defaults:
    _controller: FL\ReportsBundle\Action\Reports\Rest\Show:__invoke
    _format: "json"

tripr_hq_api_reports_delete:
  path: /reports/{reportName}
  methods: [DELETE]
  defaults:
    _controller: FL\ReportsBundle\Action\Reports\Rest\Delete:__invoke
    _format: "json"
  options:
      expose: true

tripr_hq_api_reports_save:
  path: /reports/{reportName}
  methods: [PUT]
  defaults:
    _controller: FL\ReportsBundle\Action\Reports\Rest\Save:__invoke
    _format: "json"
  options:
      expose: true

tripr_hq_api_reports_build:
  path: /reports_build
  methods: [POST]
  defaults:
    _controller: FL\ReportsBundle\Action\Reports\Rest\Build:__invoke
    _format: "json"
  options:
      expose: true